LANGUAGE_PACKS = {
    "ko": {
        "name": "Korean",
        "voice": "ko-KR-SunHiNeural",
        "suffix": "ko",
        "keyPoints": "핵심 포인트",
        "buyerCheck": "구매 전 확인",
        "whatStandsOut": "주목할 점",
        "bottomLine": "한 줄 결론",
        "pros": "장점",
        "cons": "단점",
        "summary": "요약",
        "fallbackLine": "실제 사용자 의견에서 반복적으로 언급된 부분을 압축했음",
        "buyerLine": "구매 전 확인하면 좋은 포인트를 간결하게 압축했음",
    },
    "en": {
        "name": "English",
        "voice": "en-US-JennyNeural",
        "suffix": "en",
        "keyPoints": "Key Points",
        "buyerCheck": "Buyer Check",
        "whatStandsOut": "What Stands Out",
        "bottomLine": "Bottom Line",
        "pros": "Pros",
        "cons": "Cons",
        "summary": "Summary",
        "fallbackLine": "A concise takeaway from repeated user feedback.",
        "buyerLine": "A concise buyer check before purchase.",
    },
    "fr": {
        "name": "French",
        "voice": "fr-FR-DeniseNeural",
        "suffix": "fr",
        "keyPoints": "Points clés",
        "buyerCheck": "À vérifier avant achat",
        "whatStandsOut": "Ce qui se distingue",
        "bottomLine": "Conclusion",
        "pros": "Points forts",
        "cons": "Points faibles",
        "summary": "Résumé",
        "fallbackLine": "Un résumé concis des avis utilisateurs les plus récurrents.",
        "buyerLine": "Un point rapide à vérifier avant l'achat.",
    },
    "de": {
        "name": "German",
        "voice": "de-DE-KatjaNeural",
        "suffix": "de",
        "keyPoints": "Kernpunkte",
        "buyerCheck": "Vor dem Kauf prüfen",
        "whatStandsOut": "Was auffällt",
        "bottomLine": "Fazit",
        "pros": "Vorteile",
        "cons": "Nachteile",
        "summary": "Zusammenfassung",
        "fallbackLine": "Eine kurze Zusammenfassung häufig genannter Nutzermeinungen.",
        "buyerLine": "Ein kurzer Check vor dem Kauf.",
    },
    "ja": {
        "name": "Japanese",
        "voice": "ja-JP-NanamiNeural",
        "suffix": "ja",
        "keyPoints": "注目ポイント",
        "buyerCheck": "購入前チェック",
        "whatStandsOut": "目立つポイント",
        "bottomLine": "結論",
        "pros": "良い点",
        "cons": "気になる点",
        "summary": "まとめ",
        "fallbackLine": "ユーザーの声でよく挙がるポイントを簡潔にまとめました。",
        "buyerLine": "購入前に確認したいポイントを簡潔にまとめました。",
    },
    "es": {
        "name": "Spanish",
        "voice": "es-ES-ElviraNeural",
        "suffix": "es",
        "keyPoints": "Puntos clave",
        "buyerCheck": "Antes de comprar",
        "whatStandsOut": "Lo más destacable",
        "bottomLine": "Conclusión",
        "pros": "Pros",
        "cons": "Contras",
        "summary": "Resumen",
        "fallbackLine": "Un resumen breve de los comentarios más repetidos por los usuarios.",
        "buyerLine": "Un punto rápido a revisar antes de comprar.",
    },
    "pt": {
        "name": "Brazilian Portuguese",
        "voice": "pt-BR-FranciscaNeural",
        "suffix": "pt",
        "keyPoints": "Pontos-chave",
        "buyerCheck": "Antes de comprar",
        "whatStandsOut": "O que se destaca",
        "bottomLine": "Conclusão",
        "pros": "Prós",
        "cons": "Contras",
        "summary": "Resumo",
        "fallbackLine": "Um resumo curto dos pontos mais citados pelos usuários.",
        "buyerLine": "Um ponto rápido para verificar antes da compra.",
    },
}


def normalize_lang(lang: str) -> str:
    lang = str(lang or "en").strip().lower()
    return lang if lang in LANGUAGE_PACKS else "en"


def get_language_pack(lang: str) -> dict:
    return LANGUAGE_PACKS[normalize_lang(lang)]
